 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/room_messages", type: :request do
  
  # RoomMessage. As you add validations to RoomMessage, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      RoomMessage.create! valid_attributes
      get room_messages_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      room_message = RoomMessage.create! valid_attributes
      get room_message_url(room_message)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_room_message_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      room_message = RoomMessage.create! valid_attributes
      get edit_room_message_url(room_message)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new RoomMessage" do
        expect {
          post room_messages_url, params: { room_message: valid_attributes }
        }.to change(RoomMessage, :count).by(1)
      end

      it "redirects to the created room_message" do
        post room_messages_url, params: { room_message: valid_attributes }
        expect(response).to redirect_to(room_message_url(RoomMessage.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new RoomMessage" do
        expect {
          post room_messages_url, params: { room_message: invalid_attributes }
        }.to change(RoomMessage, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post room_messages_url, params: { room_message: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested room_message" do
        room_message = RoomMessage.create! valid_attributes
        patch room_message_url(room_message), params: { room_message: new_attributes }
        room_message.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the room_message" do
        room_message = RoomMessage.create! valid_attributes
        patch room_message_url(room_message), params: { room_message: new_attributes }
        room_message.reload
        expect(response).to redirect_to(room_message_url(room_message))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        room_message = RoomMessage.create! valid_attributes
        patch room_message_url(room_message), params: { room_message: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested room_message" do
      room_message = RoomMessage.create! valid_attributes
      expect {
        delete room_message_url(room_message)
      }.to change(RoomMessage, :count).by(-1)
    end

    it "redirects to the room_messages list" do
      room_message = RoomMessage.create! valid_attributes
      delete room_message_url(room_message)
      expect(response).to redirect_to(room_messages_url)
    end
  end
end
